"""add is_admin + disabled

Revision ID: 420d8400898a
Revises: 7fc9d6e1fe48
Create Date: 2026-07-03 01:00:32.446501
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '420d8400898a'
down_revision: Union[str, None] = '7fc9d6e1fe48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('disabled')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
