"""mcp servers catalog + group_mcp

Revision ID: 5d54dbf59457
Revises: d5d6f199d2ec
Create Date: 2026-07-03 20:16:03.625644
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d54dbf59457'
down_revision: Union[str, None] = 'd5d6f199d2ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('transport', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('auth_type', sa.String(), nullable=False),
    sa.Column('token_encrypted', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_servers_name'), ['name'], unique=True)

    op.create_table('group_mcp',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('mcp_server_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_group_mcp_group_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], name='fk_group_mcp_mcp_server_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'mcp_server_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_mcp')
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_servers_name'))

    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
