"""add user voice

Revision ID: aa4dbcb609fc
Revises: 5d54dbf59457
Create Date: 2026-08-18 10:06:05.638762
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa4dbcb609fc'
down_revision: Union[str, None] = '5d54dbf59457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice', sa.String(), server_default='F2', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('voice')

    # ### end Alembic commands ###
