"""kb group_id + is_public

Revision ID: d5d6f199d2ec
Revises: 7e41d408adb9
Create Date: 2026-07-03 07:26:45.218813
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd5d6f199d2ec'
down_revision: Union[str, None] = '7e41d408adb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_kb_files_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_kb_files_group_id_groups', 'groups', ['group_id'], ['id'], ondelete='SET NULL'
        )

    # Back-fill: existing KB docs pre-date groups. Make them public so they stay
    # visible to everyone after the gate flips on (an admin can re-file into
    # groups later). Session docs are unaffected (never matched by the kb branch).
    # NOTE: the denormalized Qdrant payload for EXISTING kb points must also be
    # patched to is_public=True — run scripts/backfill_kb_public_payload.py on
    # deploy (see that script). New ingests carry the fields automatically.
    op.execute("UPDATE kb_files SET is_public = 1 WHERE scope = 'kb'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_files', schema=None) as batch_op:
        batch_op.drop_constraint('fk_kb_files_group_id_groups', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_kb_files_group_id'))
        batch_op.drop_column('is_public')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
